name: pictora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.3.0
  file_selector: ^1.0.3
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0  # Add the QR code package
  path_provider: ^2.0.2  # Add the path provider package
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.3
  pretty_qr_code: ^3.0.0
  firebase_database: ^11.2.0
  mobile_scanner: ^6.0.2
  firebase_core: ^3.6.0
  firebase_app_check: 0.3.1+7
  cached_network_image: ^3.2.3
  image: ^4.3.0
  flutter_cache_manager: ^3.3.0
  flutter_email_sender: ^6.0.3
  mailer: ^6.3.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.jpg
    - assets/hpbg1.png
